plugins { id 'com.android.application' }

android {
    namespace 'com.dsh.fakedevice'
    compileSdk 34
    defaultConfig {
        applicationId "com.dsh.fakedevice"
        minSdk 24
        targetSdk 34
        versionCode 1
        versionName "1.0"
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
    buildTypes {
        release { minifyEnabled false }
    }
    lint { abortOnError false }
}

dependencies {
    compileOnly 'de.robv.android.xposed:api:82'
}
